export enum LogicBlockType {
  SET_VARIABLE = "Set variable",
  CONDITION = "Condition",
  REDIRECT = "Redirect",
  SCRIPT = "Code",
  TYPEBOT_LINK = "Typebot link",
  WAIT = "Wait",
  AB_TEST = "AB test",
  WEBHOOK = "webhook",
  JUMP = "Jump",
  RETURN = "Return",
  GET_CONTACT = "Get contact",
  SET_CONTACT = "Set contact",
  ADD_TAG = "Add tag",
  REMOVE_TAG = "Remove tag",
}
